treatments:
  - name: human x 2 (none)
    factorIds:
      - fXPTZpBnxsxuotxh6
      - FccqQDekPjChDLavW
      - uimy8Qk7rRFkgdcx5
      - stSByaLq2axRCzySD
      - sCsrr2mz5qdeCGS4T
      - CJQ74eCpLbH4m8yMK
      - MPo9Ke8af28eSNtTK
  - name: human + bot (global)
    factorIds:
      - fXPTZpBnxsxuotxh6
      - GbiyWT2nipp7BNvak
      - stSByaLq2axRCzySD
      - sCsrr2mz5qdeCGS4T
      - CJQ74eCpLbH4m8yMK
      - 2zkyc3vkB5t4umaR7
      - MPo9Ke8af28eSNtTK
  - name: human + bot (local)
    factorIds:
      - fXPTZpBnxsxuotxh6
      - bfkBvo32jL2b55Ywo
      - stSByaLq2axRCzySD
      - sCsrr2mz5qdeCGS4T
      - CJQ74eCpLbH4m8yMK
      - 2zkyc3vkB5t4umaR7
      - MPo9Ke8af28eSNtTK
  - name: human + bot (interactive)
    factorIds:
      - fXPTZpBnxsxuotxh6
      - mszqCDRNwD78yCezK
      - stSByaLq2axRCzySD
      - sCsrr2mz5qdeCGS4T
      - CJQ74eCpLbH4m8yMK
      - 2zkyc3vkB5t4umaR7
      - MPo9Ke8af28eSNtTK
  - name: human no feedback
    factorIds:
      - x8NsYrN2aEXJ9ns8k
      - uimy8Qk7rRFkgdcx5
      - stSByaLq2axRCzySD
      - sCsrr2mz5qdeCGS4T
      - CJQ74eCpLbH4m8yMK
      - FccqQDekPjChDLavW
      - 4xEeuoadBeeujy4nH
  - name: human mult stages
    factorIds:
      - x8NsYrN2aEXJ9ns8k
      - uimy8Qk7rRFkgdcx5
      - sCsrr2mz5qdeCGS4T
      - CJQ74eCpLbH4m8yMK
      - FccqQDekPjChDLavW
      - MPo9Ke8af28eSNtTK
    archivedAt: 2019-04-10T20:10:13.677Z
  - name: human mult stages
    factorIds:
      - x8NsYrN2aEXJ9ns8k
      - uimy8Qk7rRFkgdcx5
      - no4NocAjd3Ny7cpxX
      - sCsrr2mz5qdeCGS4T
      - CJQ74eCpLbH4m8yMK
      - FccqQDekPjChDLavW
      - MPo9Ke8af28eSNtTK
factorTypes:
  - _id: dQGvpt4f73WYXEkxZ
    name: playerCount
    description: The Number of players participating in the given game.
    required: true
    type: Integer
    min: 1
  - _id: Nooz2W7GnyGFZWgTB
    name: interpretationType
    description: Interpretation provided for AI
    required: false
    type: String
  - _id: ZRZ6Cj3NziZauB3bA
    name: roundCount
    description: Number of rounds played
    required: false
    type: Integer
    min: 1
    max: 100
  - _id: Jroupzjefq85xtNGj
    name: stageLength
    description: Number of seconds in stage
    required: false
    type: Integer
    min: 1
    max: 12000
  - _id: KfyLA4vySCuJ8RYAX
    name: socialStageLength
    description: Number of seconds in social stage
    required: false
    type: Integer
    min: 1
    max: 12000
  - _id: 4q2RSFfsrB3oFRTu6
    name: botsCount
    description: Number of bots
    required: false
    type: Integer
    min: 0
    max: 100
  - _id: zmLFe9T5uH7cAGo4n
    name: giveFeedback
    description: Show score to users.
    required: false
    type: Boolean
factors:
  - _id: MPo9Ke8af28eSNtTK
    name: 'true'
    value: true
    factorTypeId: zmLFe9T5uH7cAGo4n
  - _id: 4xEeuoadBeeujy4nH
    name: 'false'
    value: false
    factorTypeId: zmLFe9T5uH7cAGo4n
  - _id: uimy8Qk7rRFkgdcx5
    name: none
    value: None
    factorTypeId: Nooz2W7GnyGFZWgTB
  - _id: bfkBvo32jL2b55Ywo
    name: local
    value: Local
    factorTypeId: Nooz2W7GnyGFZWgTB
  - _id: GbiyWT2nipp7BNvak
    name: global
    value: Global
    factorTypeId: Nooz2W7GnyGFZWgTB
  - _id: x8NsYrN2aEXJ9ns8k
    name: one
    value: 1
    factorTypeId: dQGvpt4f73WYXEkxZ
  - _id: fXPTZpBnxsxuotxh6
    name: two
    value: 2
    factorTypeId: dQGvpt4f73WYXEkxZ
  - _id: stSByaLq2axRCzySD
    name: one
    value: 1
    factorTypeId: ZRZ6Cj3NziZauB3bA
  - _id: no4NocAjd3Ny7cpxX
    name: three
    value: 3
    factorTypeId: ZRZ6Cj3NziZauB3bA
  - _id: WxmdRvjuc2rBaw3K2
    name: short
    value: 60
    factorTypeId: Jroupzjefq85xtNGj
  - _id: Q7bKTC87PQNjfNfmn
    name: normal
    value: 120
    factorTypeId: Jroupzjefq85xtNGj
  - _id: sCsrr2mz5qdeCGS4T
    name: long
    value: 12000
    factorTypeId: Jroupzjefq85xtNGj
  - _id: 8GmjZDHGTdzgTSawA
    name: short
    value: 60
    factorTypeId: KfyLA4vySCuJ8RYAX
  - _id: pKR6aPvBL5wyDBjbZ
    name: normal
    value: 120
    factorTypeId: KfyLA4vySCuJ8RYAX
  - _id: CJQ74eCpLbH4m8yMK
    name: long
    value: 12000
    factorTypeId: KfyLA4vySCuJ8RYAX
  - _id: 2zkyc3vkB5t4umaR7
    name: one
    value: 1
    factorTypeId: 4q2RSFfsrB3oFRTu6
  - _id: mszqCDRNwD78yCezK
    name: interactive
    value: Interactive
    factorTypeId: Nooz2W7GnyGFZWgTB
  - _id: FccqQDekPjChDLavW
    name: zero
    value: 0
    factorTypeId: 4q2RSFfsrB3oFRTu6
lobbyConfigs:
  - name: long
    timeoutType: lobby
    timeoutInSeconds: 12000
    timeoutStrategy: fail
    gameLobbyIds: []
